In [8]:
import numpy as np
import tensorflow as tf
import torch 


In [9]:
N = 10 #data 
#each data point as one input and output value
D_in = 1 
D_out =1 
#random array 
X = torch.randn(N,D_in) #input data
#true W and B values 

#model will never see true_W and True_B 
true_W = torch.tensor([[2.0]])  
true_B = torch.tensor (1.0)
y_true = X @ true_W + true_B + torch.randn(N, D_out)*0.1 #0.1 is a bit of noise at the end 

#create the brain 
W = torch.randn(D_in,D_out,requires_grad=True)
B = torch.randn(1,requires_grad=True)

print(f"initial weight w:\n {W}\n")
print(f"initial bias B:\n {B}\n") #model initial hypothesis

#implement 
y_hat = X@W + B 

print(f"prediction y_hat (first 3 rows):\n{y_hat[:3]}\n")
print(f"true Labels y_true :\n{y_true[:3]}\n")


initial weight w:
 tensor([[1.1355]], requires_grad=True)

initial bias B:
 tensor([-1.2081], requires_grad=True)

prediction y_hat (first 3 rows):
tensor([[ 0.1728],
        [-2.2257],
        [-1.4764]], grad_fn=<SliceBackward0>)

true Labels y_true :
tensor([[ 3.4062],
        [-0.7789],
        [ 0.5841]])



In [ ]:
error = y_hat - y_true 
squared  = error ** 2
loss = squared.mean()
print (f"loss: \n{loss}\n")

loss: 
6.845776557922363



In [11]:
loss.backward() # pytorch will computer .gradAttribute  => how to adjust the nods
# by finding the derivative we can find the direction ! 

#now lets act on this 
#training loop => learning 
#Gradient Descent 

#math theta_t+1 = theta_t - learning_rate * gradient*Loss

# Epochs => how many times we will update (a cycle of learning process)

#torch.no_grad() => dont update parameter updates 
#.grad.zero_() => reset gradients each iteratin very important 



In [25]:
#hyperparameters
learning_rate = 0.01
epochs =1000
W = torch.randn(1,1,requires_grad=True)
B= torch.randn(1,requires_grad=True)

for epoch in range(epochs):
    y_hat =X@W+B
    loss = torch.mean((y_hat-y_true)**2)
    loss.backward()
    with torch.no_grad():
        W -= learning_rate*W.grad
        B -= learning_rate*B.grad
    W.grad.zero_()
    B.grad.zero_() 
    if epoch %10 == 0:
        print (f"epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.3f}, B={B.item():.3f}")

print(f"\n Final Parameters: W={W.item():.3f}, B={B.item():.3f}")


epoch 00: Loss=2.9313, W=0.659, B=0.113
epoch 10: Loss=1.8298, W=0.866, B=0.364
epoch 20: Loss=1.1526, W=1.034, B=0.556
epoch 30: Loss=0.7348, W=1.170, B=0.702
epoch 40: Loss=0.4759, W=1.282, B=0.813
epoch 50: Loss=0.3143, W=1.374, B=0.897
epoch 60: Loss=0.2126, W=1.450, B=0.960
epoch 70: Loss=0.1479, W=1.514, B=1.007
epoch 80: Loss=0.1061, W=1.568, B=1.041
epoch 90: Loss=0.0785, W=1.613, B=1.065
epoch 100: Loss=0.0600, W=1.652, B=1.082
epoch 110: Loss=0.0472, W=1.685, B=1.094
epoch 120: Loss=0.0381, W=1.714, B=1.101
epoch 130: Loss=0.0314, W=1.739, B=1.105
epoch 140: Loss=0.0264, W=1.761, B=1.107
epoch 150: Loss=0.0226, W=1.781, B=1.107
epoch 160: Loss=0.0195, W=1.798, B=1.106
epoch 170: Loss=0.0170, W=1.814, B=1.104
epoch 180: Loss=0.0150, W=1.827, B=1.101
epoch 190: Loss=0.0133, W=1.840, B=1.098
epoch 200: Loss=0.0119, W=1.851, B=1.094
epoch 210: Loss=0.0107, W=1.861, B=1.091
epoch 220: Loss=0.0097, W=1.871, B=1.087
epoch 230: Loss=0.0089, W=1.879, B=1.084
epoch 240: Loss=0.0081, W=

In [26]:
# The input to our model has 1 feature (D_in=1)
# The output of our model is 1 value (D_out=1)
D_in = 1
D_out = 1

# Create a Linear layer
linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

# You can inspect the randomly initialized parameters inside
print(f"Layer's Weight (W): {linear_layer.weight}\n")
print(f"Layer's Bias (b): {linear_layer.bias}\n")

# You use it just like a function. Let's pass our data X through it.
# This performs the forward pass: X @ W.T + b
# (Note: nn.Linear stores W as (D_out, D_in), so it uses a transpose)
y_hat_nn = linear_layer(X)

print(f"Output of nn.Linear (first 3 rows):\n {y_hat_nn[:3]}")

Layer's Weight (W): Parameter containing:
tensor([[-0.9676]], requires_grad=True)

Layer's Bias (b): Parameter containing:
tensor([-0.0198], requires_grad=True)

Output of nn.Linear (first 3 rows):
 tensor([[-1.1966],
        [ 0.8473],
        [ 0.2088]], grad_fn=<SliceBackward0>)
